import '../globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Navbar from '../components/navbar/navbar';
import ClientOnly from '../components/ClientOnly';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Your Calender',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <>
            <ClientOnly>
                <Navbar />
            </ClientOnly>
            {children}
        </>
    );
}
