import '../globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Navbar from '../components/navbar/navbar';
import ClientOnly from '../components/ClientOnly';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'New Bookings',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <div>
            <Navbar />
            <div>{children}</div>
        </div>
    );
}
